# Generated by Django 5.0.4 on 2024-04-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_cadastro_usuario_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_usuario',
            name='senha',
            field=models.CharField(max_length=256),
        ),
    ]
