# Generated by Django 5.0.4 on 2024-04-26 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_alter_cadastro_usuario_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Forum.topico'),
        ),
    ]
