# Generated by Django 5.0.4 on 2024-04-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0004_alter_comentario_topico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_usuario',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cadastro_usuario',
            name='sobrenome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='conteudo',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='topico',
            name='assunto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='topico',
            name='mensagens',
            field=models.CharField(max_length=2000),
        ),
    ]
