# Generated by Django 5.0.4 on 2024-04-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0005_alter_cadastro_usuario_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('C', 'Comum'), ('A', 'Administrador')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='comentario',
            name='status_comentario',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='topico',
            name='status_post',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1),
        ),
    ]
