# Generated by Django 5.0.4 on 2024-04-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0006_cadastro_usuario_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_usuario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Não Informar')], max_length=1, null=True),
        ),
    ]
